// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzTRl4sOvvvBJQDgUEBsIfXeoqPsBvAFs',
    appId: '1:291304286696:web:7140cc068add091b3d9c5d',
    messagingSenderId: '291304286696',
    projectId: 'my-mirai-63ead',
    authDomain: 'my-mirai-63ead.firebaseapp.com',
    storageBucket: 'my-mirai-63ead.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsLYZtnPsWIP2pf-OcwoYB5aJy1Y6oMeo',
    appId: '1:291304286696:android:e23cbefa82849a123d9c5d',
    messagingSenderId: '291304286696',
    projectId: 'my-mirai-63ead',
    storageBucket: 'my-mirai-63ead.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2dRGg--jSJhIN-CnQoLdataaoe_B7FtI',
    appId: '1:291304286696:ios:9dc6c3c0ed2128673d9c5d',
    messagingSenderId: '291304286696',
    projectId: 'my-mirai-63ead',
    storageBucket: 'my-mirai-63ead.firebasestorage.app',
    iosBundleId: 'com.mymirai.myMirai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2dRGg--jSJhIN-CnQoLdataaoe_B7FtI',
    appId: '1:291304286696:ios:9dc6c3c0ed2128673d9c5d',
    messagingSenderId: '291304286696',
    projectId: 'my-mirai-63ead',
    storageBucket: 'my-mirai-63ead.firebasestorage.app',
    iosBundleId: 'com.mymirai.myMirai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzTRl4sOvvvBJQDgUEBsIfXeoqPsBvAFs',
    appId: '1:291304286696:web:47aebd00d5cbbf523d9c5d',
    messagingSenderId: '291304286696',
    projectId: 'my-mirai-63ead',
    authDomain: 'my-mirai-63ead.firebaseapp.com',
    storageBucket: 'my-mirai-63ead.firebasestorage.app',
  );
}
